"""
config.py
Central configuration for the algo-trader-india project.
"""

# Filtered universe for RSI(2) mean reversion.
# Generated by src/filter_universe.py with criteria:
#   - >= 1000 trading days of history (~4 years)
#   - Price between Rs 50 and Rs 1000 (affordable, not penny)
#   - Daily return volatility under 4%
# Manually removed GOLDBEES (gold doesn't mean-revert like equities)
# and NIFTYBEES (index ETF, averaged-out, theoretical mismatch).

WATCHLIST = [
    "AARTIIND.NS",
    "ANANTRAJ.NS",
    "ANGELONE.NS",
    "APTUS.NS",
    "ASTERDM.NS",
    "BANDHANBNK.NS",
    "BLS.NS",
    "BRIGADE.NS",
    "CAMS.NS",
    "CASTROLIND.NS",
    "CESC.NS",
    "CHAMBLFERT.NS",
    "COALINDIA.NS",
    "COHANCE.NS",
    "CROMPTON.NS",
    "CUB.NS",
    "DEVYANI.NS",
    "FSL.NS",
    "GMDCLTD.NS",
    "GPIL.NS",
    "HBLENGINE.NS",
    "HINDCOPPER.NS",
    "HSCL.NS",
    "IDBI.NS",
    "IFCI.NS",
    "IGL.NS",
    "IIFL.NS",
    "INOXWIND.NS",
    "IRCON.NS",
    "ITC.NS",
    "ITI.NS",
    "JBMA.NS",
    "JMFINANCIL.NS",
    "KARURVYSYA.NS",
    "KEC.NS",
    "MANAPPURAM.NS",
    "MRPL.NS",
    "NATCOPHARM.NS",
    "NBCC.NS",
    "ONGC.NS",
    "PGEL.NS",
    "POONAWALLA.NS",
    "RAMCOCEM.NS",
    "RBLBANK.NS",
    "REDINGTON.NS",
    "SARDAEN.NS",
    "SBIN.NS",
    "SONACOMS.NS",
    "STARHEALTH.NS",
    "SYNGENE.NS",
    "TATACHEM.NS",
    "TATAPOWER.NS",
    "TRITURBINE.NS",
    "WHIRLPOOL.NS",
    "WIPRO.NS",
    "ZENSARTECH.NS",
]

PERIOD = "5y"
INTERVAL = "1d"
DATA_DIR = "data"
